# Generated by Django 3.2.16 on 2022-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '未知'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, '审核'), (2, '拒绝'), (1, '通过')], default=0, verbose_name='审核status'),
        ),
    ]
